version: '3'

services:
  virtuoso:
    build:
      context: .
      dockerfile: ./virtuoso.Dockerfile
    ports:
    - "8003:8890"
    command: /virtuoso_start.sh
  seek:
    build:
      context: .
      dockerfile: ./seek.Dockerfile
    ports:
    - "8002:3000"
    depends_on:
    - virtuoso
  galaxy:
    build:
      context: .
      dockerfile: ./galaxy.Dockerfile
    ports:
    - "8001:80"
  myfair:
    build:
      context: .
      dockerfile: ./myFAIR.Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - seek
      - galaxy
      - virtuoso

    